### ISSUE TITLE
Create `format` function

### ISSUE THREAD

**Issue by MBattagl** [MethodsConsultants/tibbletest#25]
Should handle spacing (for categorical variables have variable name and p-value on own row with one row per label), p-value rounding, adding Ns to column names, and applying variable labels (may need to be done in `descriptives`).

**Comment by MBattagl** [comment]
@scheidec What is the best way to add Ns to column names within `format`? Currently the `descriptives` output is just the summary tibble, and there is no way to get Ns for the treatment groups from just this object. Should we have `descriptives` add the Ns to the output tibble as an attribute?

**Comment by scheidec** [comment]
Yeah it would be the most efficient to have them preserved from the `descriptives` function somehow.  If it's easiest to store the counts as an attribute that would work.
