### ISSUE TITLE
Switch back to survey for p-values

### ISSUE THREAD

**Issue by MBattagl** [MethodsConsultants/tibbletest#27]
@scheidec 

I'm leaning toward switching back to the `survey` package for p-value calculation. We're currently using `survey` for kruskal-wallis, but manipulations on base functions for chi-squared and anova. 

It seems that specifying weights in `lm` gives accurate coefficient estimates, but does not appropriately adjust the SE and p-value. I don't have specific concerns about our current chi-squared approach, but I feel more comfortable in `survey` handling things correctly. 

The one thing that turned me off from `survey` was that it doesn't match the base functions when passing in weights of all 1. In our kruskal-wallis function there is an if/else block where the base test is used if weights are all 1, and survey otherwise. Is this the approach we should take, or is it better to use `survey` for everything?

**Comment by scheidec** [comment]
I like the idea of using `survey` everywhere, with the if/else block using the base test if weights are all 1.  What exactly is different in that case when using the `survey` package?

**Comment by MBattagl** [comment]
Just a slightly different p-value. Probably just different defaults or optimization technique

**Comment by scheidec** [comment]
Alright, it might make sense then to just use `survey` in all cases to be consistent

**Comment by MBattagl** [comment]
I'm torn on this. I like the idea of being consistent, but I also think that it not returning the same values as the base tests would be unexpected behavior for a new user.

**Comment by scheidec** [comment]
As long as it is made clear in the documentation that all weighted tests are based off of the `survey` package functions, I think it's fine to use that everywhere.
